name: Test Colab Notebook

on:
  push:
  workflow_dispatch:

jobs:
  test-colab-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.5.3
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh

      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10 

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install google-colab -c conda-forge
          jupyter --version

      - name: Test Google Colab Notebook with CLI shell commands
        run: jupyter nbconvert --to notebook --execute notebooks/test-colab-notebook-cli.ipynb --output=output-cli.ipynb --ExecutePreprocessor.timeout=-1

      - name: Test Google Colab Notebook with Python API commands
        run: jupyter nbconvert --to notebook --execute notebooks/test-colab-notebook-python-api.ipynb --output=output-python-api.ipynb --ExecutePreprocessor.timeout=-1

      - name: Upload Output of the Google Colab Notebook CLI
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v3.1.2
        with:
          name: output-cli.ipynb
          path: notebooks/output-cli.ipynb
          retention-days: 7

      - name: Upload Output of the Google Colab Notebook Python API
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v3.1.2
        with:
          name: output-python-api.ipynb
          path: notebooks/output-python-api.ipynb
          retention-days: 7
